### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by viankakrisna** [zenato/puppeteer-renderer#1]
Hi, thank you for building this! I have been using it and I think it has a great potential, especially if it more configurable via the URL. Right now it only has `url` and `type`, I think it's good that if we have another:

- `waitUntil`
- `waitForSelector`
- `width`
- `height`
- `fullPage`

**Comment by zenato** [comment]
For security reasons, only some parameters are provided via web.
I am thinking about how to improve it.
If possible, send a pull request.

**Comment by Vineeth-Mohan** [comment]
@zenato  - Please comment on how many parllel pages can be rendered and put some options on that too.

**Comment by zenato** [comment]
@Vineeth-Mohan - Renderer doesn't have request throttling(or queue). Performance will vary depending on the processing speed of the page or the specifications of the system.
Currently I'm thinking of adding some options. (It seems to take some time.)
Thanks for your comment.

**Comment by zenato** [comment]
I have added some extra parameter for PDF / screenshot.
Almost options added, but object type options are not applied.
If you have a good idea, send PR.
