### ISSUE TITLE
How should it work?

### ISSUE THREAD

**Issue by vvscode** [zenato/puppeteer-renderer#16]
Hi, @zenato 

Just wonder about the idea (I'm surprised that can't see this question in issues).

We have next in middleware:

```javascript
let isRender = false

module.exports = function(options) {
  if (!options || !options.url) {
    throw new Error('Must set url.')
  }

  let rendererUrl = options.url

  const userAgentPattern = options.userAgentPattern || new RegExp(botUserAgents.join('|'), 'i')
  const excludeUrlPattern =
    options.excludeUrlPattern || new RegExp(`\\.(${staticFileExtensions.join('|')})$`, 'i')
  const timeout = options.timeout || 10 * 1000

  return (req, res, next) => {
    if (isRender) return next()
    isRender = true
```

My concern is that `isRender` flag. On first request it's false. That's fine. We can run our logic to detect bot and so. After first call you make it `true`. And it makes middleware ignore all the following requests.

What's the idea?

**Comment by zenato** [comment]
@vvscode It was huge mistake.The `isReder` flag was designed for cache, but decided not to implement the cache. But I didn't delete this flag and did commit.
Thank you for let me know. I fixed it.
