### ISSUE TITLE
API to generate jpeg file

### ISSUE THREAD

**Issue by virtualorz** [zenato/puppeteer-renderer#18]
Hi, I want to use api to generate jpeg file, but the screenshot option 'type' can not use, because in the URL already has 'type' parameter for choose pdf or screenshot, please help thanks.

**Comment by zenato** [comment]
@virtualorz I appended screenshot image parameter a bit ago.
`http://localhost:3000/?url=http://google.com&type=screenshot&screenshotType=jpeg`
