### ISSUE TITLE
media for pdf

### ISSUE THREAD

**Issue by arius28** [zenato/puppeteer-renderer#25]
Hi, I am trying to understand if I can export the pdf with emulatemedia as screen but it seems that this can't be altered because it is hardcoded to always use print? Or am I not using the url varaibles properly?

I tried media, emulateMedia, mediaType & emulateMedia.mediaType none of which gave me any different results. 

If I am reading this line 
https://github.com/zenato/puppeteer-renderer/blob/8287d18d3104f9f136f08082cca488050288ee90/src/renderer.js#L46

correctly and it is hardcoded is there a chance you might leave it as an option in the URL and if it is not provided then by default use 'print'?

Thank you for taking the time to build and maintain this image!

**Comment by zenato** [comment]
@arius28 I've been added that options. Please check again. 
Thank you for your proposal.

**Comment by arius28** [comment]
@zenato It works fine now. Thank you!!
