### ISSUE TITLE
Docker container fails to run

### ISSUE THREAD

**Issue by AdityaAnand1** [zenato/puppeteer-renderer#33]
```
> puppeteer-renderer@0.17.2 start /app
> node src/index.js

(node:18) ExperimentalWarning: The fs.promises API is experimental
Fail to initialze renderer. Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to downlo
ad a browser binary.
    at ChromeLauncher.launch (/app/node_modules/puppeteer/lib/Launcher.js:59:23)

```

After building a custom docker container from the source using `docker build -t imagename .` and then running `docker running imagename`, I'm getting the above error message, looks like the dependencies aren't being installed properly.

Any ideas how to fix this?

**Comment by zenato** [comment]
@AdityaAnand1 I updated base docker image and puppeteer library version. 
Please delete the image you received, pull it back, and then try.
Thanks.
