### ISSUE TITLE
How to pass additional options for clipping

### ISSUE THREAD

**Issue by seigieu** [zenato/puppeteer-renderer#36]
I've looked at extra options, however these does not seem to work. From Docs `clip.y` should work with screenshots, but I get 500 error. How should I build query to be able to clip (or scroll site)?

```
<?php
 $params['width'] = 1200;
    $params['height'] = 600;
    $params['margin.top'] = 100;
    $params['options.clip.y'] = 120; // No effect
    $params['clip.y'] = 120; // Error 500
    $params['clip']['y'] = 120; // Error 500
    $params['type'] = 'screenshot';
//    header('Content-type: image/png');
    echo file_get_contents(SCREENSHOT_API_URL . http_build_query($params));
```

**Comment by zenato** [comment]
@seigieu I fixed it.
I updated puppeteer module version few days ago and I think the bugs occurred then.
Thanks for your report.

**Comment by seigieu** [comment]
@zenato  Sorry to say...
From `package.json` => `2.0.3`
Then

```
Error 500: Oops, An expected error seems to have occurred.Error: Expected options.clip.x to be a number but found string
Params: width=1200&height=600&animationTimeout=3600&clip.x=120&type=screenshot

Error 500: Oops, An expected error seems to have occurred.Error: Expected options.clip.x to be a number but found undefined
Params: width=1200&height=600&animationTimeout=3600&clip.y=120&type=screenshot

Error 500: Oops, An expected error seems to have occurred.Error: Expected options.clip.x to be a number but found undefined
Params: width=1200&height=600&animationTimeout=3600&clip%5By%5D=120&type=screenshot
```

**Comment by seigieu** [comment]
@zenato  ?? Do I do something wrong?

**Comment by seigieu** [comment]
@zenato Problem persists

**Comment by zenato** [comment]
@seigieu I've checked that there are something wrong with parameter casting.
And I fixed so that parameters can be converted correctly.

See below. Thanks.

http://localhost:3000/?url=google.com&width=1200&height=600&animationTimeout=3600&clip.x=100&clip.y=120&clip.width=100&clip.height=100&type=screenshot

**Comment by seigieu** [comment]
Great, thank you! Works like a charm in 2.1.0!
