### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by gacekssj4** [zenato/puppeteer-renderer#37]
Some websites (mainly internal ones, so may be routing issue) is giving me error 500 while trying to take a screenshot. Is it possible to display errors somehow what caused 500? Or access any logs?

**Comment by gacekssj4** [comment]
I managed to get my error

`Oops, An expected error seems to have occurred.Error: net::ERR_CONNECTION_REFUSED`
So it is networking problem.

If anyone ever needs to see error from docker then I edited this line
https://github.com/zenato/puppeteer-renderer/blob/8c91556d49db75d117df0f67bb14259ce8e1da1f/src/index.js#L88 
Replacing it with `res.status(500).send("Oops, An expected error seems to have occurred." + err);`

@zenato you can close it or maybe add some debugging. I'm leaving it you your decision :)

**Comment by zenato** [comment]
@gacekssj4 Thanks for your opinion.

I think it's hard to include details on the error page.
Because it may contain content that is unnecessary for the user or is not good for security.

Please check server logs If you have any problem.
Thanks.

**Comment by gacekssj4** [comment]
@zenato Thank you for your reply. Actually i still didn't find server logs location. Where does this docker app log errors to?

**Comment by zenato** [comment]
@gacekssj4 
You can see docker log with below command.
`docker logs your_container_name`

**Comment by gacekssj4** [comment]
@zenato So obvious solution, and I overlooked it.... thank you.
