### ISSUE TITLE
no old tags available on docker hub`

### ISSUE THREAD

**Issue by cdaringe** [zenato/puppeteer-renderer#4]
# problem

newly released version of this image break my tests.  admittedly i use it in a pretty hacky way!  i would like to stay pinned to the last release, not the latest release

# discussion

can we publish tagged images on dockerhub vs just latest?

thx!

**Comment by zenato** [comment]
@cdaringe I published old version. Thank you for comment.

**Comment by cdaringe** [comment]
thx!
