### ISSUE TITLE
Puppeter cache disable or clear

### ISSUE THREAD

**Issue by gacekssj4** [zenato/puppeteer-renderer#40]
Is there a way to clear puppeter/docker cache? Preferably by parameter. 

I render preview and then when I change image on server renderer does not see it. Holds html image in cache.

Is there a way to force puppeteer docker api to disable caching or force to refresh it?

**Comment by zenato** [comment]
@gacekssj4
I've  set cache configuration when create page.
Thanks.

**Comment by seigieu** [comment]
Great, thank you!
