### ISSUE TITLE
animationTimeout shouldn't cause exceptions with fullPage (before the timeout passes, at least)

### ISSUE THREAD

**Issue by jason-o-matic** [zenato/puppeteer-renderer#43]
I've noticed occasional exceptions in
https://github.com/zenato/puppeteer-renderer/blob/master/src/wait-for-animations.js#L18

I think what's happening is JS is causing the page to change size, then the image returned by `page.screenshot` is a different size than `previous`. This results in an exception from pixelmatch:
https://github.com/mapbox/pixelmatch/blob/master/bin/pixelmatch#L26

Off the top of my head I'd prefer the loop just keep checking until the timeout expires, then return false if for some reason it still didn't match.

**Comment by zenato** [comment]
@jason-o-matic Thanks for your report.

The pixel matching error seems to be due to the animation not finished yet.
I think you should set more time to `animationTimeout`.

And I couldn't agree with your suggestion that wait until matching size.
Even if animation is not finished yet, I think `anmationTimeout` option shouldn't wait more.

**Comment by jason-o-matic** [comment]
Thanks for the prompt reply!

Here's a stack trace with more info, with an example that I think indicates more `animationTimeout` isn't the only problem.
```
$ time curl 'http://localhost:3000/?type=screenshot&fullPage=true&animationTimeout=9999999999&url=https://www.cnn.com/'
Oops, An expected error seems to have occurred.
real	0m23.766s
user	0m0.015s
sys	0m0.039s
$ docker logs foobar

> puppeteer-renderer@2.1.1 start /app
> node src/index.js

Initialized renderer.
Listen port on 3000.
Error: Image sizes do not match.
    at pixelmatch (/app/node_modules/pixelmatch/index.js:21:15)
    at waitForAnimations (/app/src/wait-for-animations.js:18:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Renderer.screenshot (/app/src/renderer.js:115:9)
    at async /app/src/index.js:61:44
```

I set the `animationTimeout` to a very large number, but the exception still happened in under 24 seconds.

I completely agree that `animationTimeout` should be the maximum amount of time to wait.

Would it be possible to add a try/catch around `pixelmatch(...)` so the calling function continued to retry?

**Comment by jason-o-matic** [comment]
> Would it be possible to add a try/catch around pixelmatch(...) so the calling function continued to retry?

Just to clarify, I mean continue to retry until reaching `animationTimeout`, but not more than that.

**Comment by zenato** [comment]
@jason-o-matic 
I misunderstood about animationTimeout problem.
So I've fixed bug by comparing data sizes.
Thanks for the detailed error reporting.

**Comment by jason-o-matic** [comment]
I can confirm this solved the issue for me, thanks!
