### ISSUE TITLE
Zombie chromium processes

### ISSUE THREAD

**Issue by WilliamNurmi** [zenato/puppeteer-renderer#50]
Hi,

We are running the `zenato/puppeteer-renderer` docker image (version `2.1.5`) on Ubuntu 18.04.3, and experiencing zombie chromium processes that slowly eat out all memory and CPU of the host machine. I suspect that the issue could be due to the [Puppeteer Process problem](https://github.com/puppeteer/puppeteer/issues/1825). The problem should be fixed in the latest puppeteer release v10.4.0.

Would it be possible to bump the puppeteer version in  puppeteer-renderer eg. to v10..40, or alternatively try one of the workarounds suggested in the above problem thread, eg. adding `--no-zygote`  to [the puppeteer launch arguments](https://github.com/zenato/puppeteer-renderer/blob/49051c25f86db544bb1cb2f1d6434ad2c1d5bdbd/src/renderer.js#L171)  as suggested in [this comment](https://github.com/puppeteer/puppeteer/issues/1825#issuecomment-636478077)

**Comment by zenato** [comment]
@WilliamNurmi I've bumped puppeteer version from v5 to v10 and published docker image. I hope your problems has been resolved.
Thanks for your bug report.
