### ISSUE TITLE
Inclusion of iframes in rendered output

### ISSUE THREAD

**Issue by arius28** [zenato/puppeteer-renderer#53]
Hi,

This could be considered more of an enhancement on your side and maybe more of a bug on the puppeteer side ??
I am using the 2.2.0 version and it seems that rendering of thumbnails from embedded youtube videos in the webpage that I am screenshot-ing is no longer possible while it was in version 2.1.5. I guess the bump in puppeteer version is to blame ??
I saw this [article](https://levelup.gitconnected.com/how-to-include-iframes-in-puppeteers-html-output-8f2f36b5f36c) regarding iframes rendering with puppeteer and wonder if this is something that could be incorporated in your side of the code to facilitate the rendering of embedded iframes. 

In my use case, I am using your docker version 2.2.0 and calling it wihtout any middleware straight through a URL like http://localhost:{port}/?url=https://www.google.com to render a webpage screenshot.

Thank you in advance for your time and work.

**Comment by zenato** [comment]
@arius28 Thanks for your issue report.
I haven't tested iframe rendering in the current version and previous version. So, it's not possible to know what kind of change the puppeteer had internally. The current project is focused on providing a kind of proxy that is convenient to use with puppeteer.

We'll check where the DOM component of the web page doesn't render properly. We will reply to you when the patch is complete.

**Comment by zenato** [comment]
@arius28 If you provide the URL and parameters used in the test, it will be helpful for debugging. Please let me know if it still works in version 2.1.5.

**Comment by arius28** [comment]
Hey zenato, Thanks for the reply.

I tried several urls. You can check https://klett.gr/webinar
The params I used where: `&type=screenshot&fullPage=true&animationTimeout=1000` . I tried several extra params and combinations but didn't manage to get anything better.

**- With version 2.1.5 I get a screenshot like this**

![renato-pup-2 1 5](https://user-images.githubusercontent.com/12183504/142936097-4d11456e-bb78-4e5e-b679-d8e043686dc5.jpg)


**- With version 2.2 I get a screenshot like this**

![renato-pup-2 2](https://user-images.githubusercontent.com/12183504/142936161-15ff0dd2-5b26-4927-9663-6a2a4f65b2e7.jpg)

Another difference is that version 2.2 throws that orange box (cookie consent) up there in the header image whereas 2.1.5 shows it at the bottom of the screenshot. The orange div element has a CSS position: fixed and bottom 0px.

I can provide you with links to the puppeteer instances to run the requests if you think it might help you further but I d' rather not put them here in the open.

**Comment by zenato** [comment]
@arius28 Thanks for your information. We fixed which problem. 
It is a problem that occurs because rendering is restricted by the security header, and the --disable-web-security option has been added to the launch arguments to solve it.
Please test it with v2.3.1 and let me know if it works.

**Comment by arius28** [comment]
Thank you very much! I will try to test it today and let you know of the results.

**Comment by arius28** [comment]
Hey @zenato,

Sorry for the extra question, but we are installing the docker image through Plesk which checks through hub.docker.com for versions and it doesn't show the new 2.3.1 version. Is it a matter of waiting for hub.docker.com to update because perhaps the list is still cached or is something else needed?

**Comment by zenato** [comment]
@arius28 
I forgot that dockerhub didn't build automatically. I pushed the new version image. please try again.

**Comment by arius28** [comment]
@zenato 
I installed it from dockerhub and it is working great.  :+1:

Thank you again for the fix!!
