### ISSUE TITLE
Multi-Architecture Images (amd64/arm64)

### ISSUE THREAD

**Issue by weph** [zenato/puppeteer-renderer#54]
Are there any plans to provide arm64 images?

**Comment by zenato** [comment]
@weph There are currently no plans, but we are testing it to deploy on arm64 in the near future.

**Comment by weph** [comment]
So there's nothing I can do to help you with this?

**Comment by zenato** [comment]
@weph You can download the current source and run it in the node.js environment. On my M1 Mac (Arm64) it is currently running. However, docker image distribution requires testing and modification.
