### ISSUE TITLE
Allow using POST method to allow for more/larger/longer options to be sent

### ISSUE THREAD

**Issue by JacoBezuidenhout** [zenato/puppeteer-renderer#61]
Thank you very much for creating and maintaining this project. 

Is there perhaps a way to POST data to the renderer instead of using GET in order to allow for things like bigger header/footer templates etc that can cause the GET url+params to become too long?

**Comment by zenato** [comment]
@JacoBezuidenhout `puppeteer-renderer` is only support GET method. And If you have any bigger params, I think you should use proxy or middleware.
