### ISSUE TITLE
Defaults for screenshots are broken

### ISSUE THREAD

**Issue by jgennari** [zenato/puppeteer-renderer#7]
Puppeteer defaults screenshots to PNG now, which means the defaults here are broken, since the PNG renderer can't have any quality set. Also since pupeteer-renderer already uses the `type` parameter, you can't override the `extraOptions` with a type of screenshot.

https://github.com/zenato/puppeteer-renderer/blob/1f9ed18e09044937efcf58401c2d807b6bdef2fb/src/renderer.js#L65

**Comment by zenato** [comment]
@jgennari Thanks for your PR.
