### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by mikkeschiren** [zenato/puppeteer-renderer#9]
Just wanted you to know that I forked this in this: https://github.com/nodeone/alpine-puppeteer-renderer - changed to Apline, updated puppeteer and added some more options. But I did a blunder and missed to get your git history in it - will fix that.

**Comment by zenato** [comment]
@mikkeschiren This project was made with the help of several people. Therefore, you should specify the location of the repository.

**Comment by mikkeschiren** [comment]
Location of repo was specified, and now also git history restored.
