### ISSUE TITLE
Path Traversal Issue

### ISSUE THREAD

**Issue by 7a6163** [zenato/puppeteer-renderer#97]
I would like to report a security issue regarding Path traversal. Attackers can use the file protocol in URL parameters to view sensitive information.

Payload:
`http://localhost:8080/html?url=file:///etc/passwd`

![image](https://github.com/zenato/puppeteer-renderer/assets/579103/41bd3428-cbda-4da9-98ef-f655c7721288)

Root cause:
The root cause is not sufficiently strict.
https://github.com/zenato/puppeteer-renderer/blob/14a6d20429a4a9e16c151d35f9f22b7d359222f7/packages/puppeteer-renderer/src/router.ts#L10

Patch:
https://github.com/zenato/puppeteer-renderer/pull/96

BTW, Can I apply for a CVE number?

**Comment by zenato** [comment]
Sorry, but I don't keep track of the CVE numbers.

**Comment by 7a6163** [comment]
> Sorry, but I don't keep track of the CVE numbers.

No problem, I'll take care of The CVE application my self. Thank you.
